//
// Created by marc on 12/3/20.
//

#ifndef DP_PARALLEL_GENERATION_CONSTS_H
#define DP_PARALLEL_GENERATION_CONSTS_H

#define MAX_CRITERIA 16
#define ERROR_NOT_DIRECTORY 5
#define ERROR_MISSING_FILES 6
#define FILE_UNOPENED 7
#define INVALID_TREE_FILE 8

#define SORT_TYPE_NONE 0
#define SORT_TYPE_TREE 1
#define SORT_TYPE_TREE_REVERSE 2
#define SORT_TYPE_FRONTIER 3
#define SORT_TYPE_FRONTIER_REVERSE 4
#define SORT_TYPE_RANDOM 5

#define COMPRESS_MODE_NONE 0
#define COMPRESS_MODE_FINAL 1
#define COMPRESS_MODE_DEPTH_STATIC 2
#define COMPRESS_MODE_THRESHOLD 3
#define COMPRESS_MODE_DEPTH_DYNAMIC 4

#define COMPRESS_DISTANCE_OBJECTIVE_SPACE 0
#define COMPRESS_DISTANCE_DECISION_SPACE 1

#define COMPRESS_LINKAGE_SINGLE 0
#define COMPRESS_LINKAGE_AVERAGE 1
#define COMPRESS_LINKAGE_COMPLETE 2

#define COMPRESS_OBJECTIVES_ALL 0
#define COMPRESS_OBJECTIVES_OPTIMIZED 1

#endif //DP_PARALLEL_GENERATION_CONSTS_H
