cc_library(
    name = "fastcluster",
    srcs = ["fastcluster.cpp"],
    hdrs = ["fastcluster.h"],
    textual_hdrs = [
        "fastcluster_dm.cpp",
        "fastcluster_R_dm.cpp"
    ],
    visibility = ["//visibility:public"]
)